/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const EducationEntry = IDL.Record({
  'year' : IDL.Nat,
  'description' : IDL.Text,
});
export const WorkExperienceEntry = IDL.Record({
  'year' : IDL.Nat,
  'description' : IDL.Text,
});
export const HonorEntry = IDL.Record({
  'year' : IDL.Nat,
  'description' : IDL.Text,
});
export const ProfessorProfile = IDL.Record({
  'bio' : IDL.Text,
  'title' : IDL.Text,
  'courses' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'education' : IDL.Vec(EducationEntry),
  'workExperience' : IDL.Vec(WorkExperienceEntry),
  'email' : IDL.Text,
  'university' : IDL.Text,
  'achievements' : IDL.Vec(IDL.Text),
  'department' : IDL.Text,
  'honors' : IDL.Vec(HonorEntry),
});

export const idlService = IDL.Service({
  'addAchievement' : IDL.Func([IDL.Text], [], []),
  'addCourse' : IDL.Func([IDL.Text], [], []),
  'addEducation' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'addHonor' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'addWorkExperience' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'createProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'getAllProfiles' : IDL.Func([], [IDL.Vec(ProfessorProfile)], ['query']),
  'getProfile' : IDL.Func([IDL.Principal], [ProfessorProfile], ['query']),
  'isProfileCreated' : IDL.Func([], [IDL.Bool], ['query']),
  'updateBio' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const EducationEntry = IDL.Record({
    'year' : IDL.Nat,
    'description' : IDL.Text,
  });
  const WorkExperienceEntry = IDL.Record({
    'year' : IDL.Nat,
    'description' : IDL.Text,
  });
  const HonorEntry = IDL.Record({ 'year' : IDL.Nat, 'description' : IDL.Text });
  const ProfessorProfile = IDL.Record({
    'bio' : IDL.Text,
    'title' : IDL.Text,
    'courses' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'education' : IDL.Vec(EducationEntry),
    'workExperience' : IDL.Vec(WorkExperienceEntry),
    'email' : IDL.Text,
    'university' : IDL.Text,
    'achievements' : IDL.Vec(IDL.Text),
    'department' : IDL.Text,
    'honors' : IDL.Vec(HonorEntry),
  });
  
  return IDL.Service({
    'addAchievement' : IDL.Func([IDL.Text], [], []),
    'addCourse' : IDL.Func([IDL.Text], [], []),
    'addEducation' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'addHonor' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'addWorkExperience' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'createProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'getAllProfiles' : IDL.Func([], [IDL.Vec(ProfessorProfile)], ['query']),
    'getProfile' : IDL.Func([IDL.Principal], [ProfessorProfile], ['query']),
    'isProfileCreated' : IDL.Func([], [IDL.Bool], ['query']),
    'updateBio' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };