/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface EducationEntry { 'year' : bigint, 'description' : string }
export interface HonorEntry { 'year' : bigint, 'description' : string }
export interface ProfessorProfile {
  'bio' : string,
  'title' : string,
  'courses' : Array<string>,
  'name' : string,
  'education' : Array<EducationEntry>,
  'workExperience' : Array<WorkExperienceEntry>,
  'email' : string,
  'university' : string,
  'achievements' : Array<string>,
  'department' : string,
  'honors' : Array<HonorEntry>,
}
export interface WorkExperienceEntry { 'year' : bigint, 'description' : string }
export interface _SERVICE {
  'addAchievement' : ActorMethod<[string], undefined>,
  'addCourse' : ActorMethod<[string], undefined>,
  'addEducation' : ActorMethod<[bigint, string], undefined>,
  'addHonor' : ActorMethod<[bigint, string], undefined>,
  'addWorkExperience' : ActorMethod<[bigint, string], undefined>,
  'createProfile' : ActorMethod<
    [string, string, string, string, string, string],
    undefined
  >,
  'getAllProfiles' : ActorMethod<[], Array<ProfessorProfile>>,
  'getProfile' : ActorMethod<[Principal], ProfessorProfile>,
  'isProfileCreated' : ActorMethod<[], boolean>,
  'updateBio' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];